### ISSUE TITLE
教材/教案找错_6：圆形等距抽样不整除时k的舍入

### ISSUE THREAD

**Issue by zhou-ziyan** [ECNUdase/DASEAlg_2020_Fall#11]
1.是否已经阅读过所在章节的已发现问题列表？
是

2.错误在PPT中出处(章节，页码，截图)?
第3课ppt，采样，14/33页
![image](https://user-images.githubusercontent.com/53011867/95566239-e37b3d00-0a53-11eb-8c17-08c037ce5503.png)

3.错误在教材中出处(章节，页码，截图)?
第2章，采样，22页，例2.6
![image](https://user-images.githubusercontent.com/53011867/95566420-19b8bc80-0a54-11eb-9f72-daf3f94d767b.png)

两者说法不一。我认为a)向下取整和b)四舍五入都可以实现圆形等距抽样中的“等概率”。ppt中不必强调需要round down

**Comment by ttliu-kiwi** [comment]
你的意思是不是在ppt里面的k应该取4而不是3？

**Comment by zhou-ziyan** [comment]
> 你的意思是不是在ppt里面的k应该取4而不是3？

是这样的！
