### ISSUE TITLE
【提问】

### ISSUE THREAD

**Issue by ningmengwei-ata** [ECNUdase/DASEAlg_2020_Fall#31]
1.是否已经阅读过所在章节的FAQ？
是

2.问题在PPT中出处(章节，页码，截图)?

3.问题在教材中出处(章节，页码，截图)?
P91 count min sketch算法
提问
tutorial 5的第二题这边
![image](https://user-images.githubusercontent.com/59048434/98433699-51269180-2104-11eb-9fe2-ba73e8a8d5a4.png)
![image](https://user-images.githubusercontent.com/59048434/98433688-35bb8680-2104-11eb-865b-6b54c2f75c51.png)

老师我想问一下，为什么这边f2的估计值是2。我计算每个元素hash值得到第二个hash函数H2对于元素的hash只会将2映射到3的位置，而数据流中只出现了一次2.
![image](https://user-images.githubusercontent.com/59048434/98433937-0dcd2280-2106-11eb-87fc-a99de878d429.png)

元素2经过三个hash映射到的位置分别是 0 3 2
对于计算频数估计值=min[2,1,4]=1
我想问一下我这样的计算过程哪边出错了呀 我这样计算出来f2的估计值是1

4.从网络搜索得到三篇参考资料并自学，请在下方附上网址。
https://en.wikipedia.org/wiki/Count%E2%80%93min_sketch
https://zhuanlan.zhihu.com/p/84688298
https://blog.csdn.net/pipisorry/article/details/64126199
5.综合学习教材、PPT、网络资源后仍然抱有疑问的原因？
不大理解计算过程中哪里出了问题
王文清

**Comment by Yuxin61** [comment]
下面的矩阵似乎不是那样的
![936565708](https://user-images.githubusercontent.com/34358935/98460598-b64fb500-21e0-11eb-9762-1a212053f1fe.jpg)

**Comment by Yuxin61** [comment]
CM Sketch中计数器数组的列数是哈希函数h_i的值域的维数而不是数据流中不同元素的个数

**Comment by ningmengwei-ata** [comment]
![image](https://user-images.githubusercontent.com/59048434/98461453-29f4c080-21e7-11eb-8d07-71c74e2b23b2.png)


我最后算出来是这样的
![image](https://user-images.githubusercontent.com/59048434/98461363-7ab7e980-21e6-11eb-8f65-3917bdc617fe.png)
我可能前面表达不清，不好意思，我的意思是 上面这张图[H2][3]的位置是1，只有2会被hash到这个位置，并且只hash了一次，所以觉得f2的估值是1
