### ISSUE TITLE
教材找错_4

### ISSUE THREAD

**Issue by Yuxin61** [ECNUdase/DASEAlg_2020_Fall#9]
1.是否已经阅读过所在章节的已发现问题列表？
是
2.错误在PPT中出处(章节，页码，截图)?
无

3.错误在教材中出处(章节，页码，截图)?
第3章，尾概率不等式及其应用，45页
![image](https://user-images.githubusercontent.com/34358935/94994950-7851e680-05cd-11eb-8a58-77849135298d.png)

Ci 是对m个Morris算法输出结果的求和，所以第11行应该是1/m吧

**Comment by ttliu-kiwi** [comment]
是的
